name: lets_yak_cli
version: 2.2.0

environment:
  sdk: ">=2.17.0 <4.0.0"

executables:
  yak: main

scripts:
  get:
    - command: flutter pub get
      cwd: packages/app/template
    - command: flutter pub get
      cwd: packages/app_brick_generator
  major:vscode: "cd extensions/vscode/scripts && bash update.sh -M"
  minor:vscode: "cd extensions/vscode/scripts && bash update.sh -m"
  build:vscode: "cd extensions/vscode/scripts && bash update.sh -p"
  build:cli:
    - command: yak run gen:app_brick
    - command: yak run bundle:all
    - command: flutter pub global activate -spath . --overwrite

  # Useful for bundling all the add bricks eg `BRICK=bloc yak run bundle`
  bundle: mason bundle ./packages/bricks/$BRICK -o ./lib/bundles/ -t dart
  bundle:app: BRICK=app yak run bundle
  bundle:component: BRICK=component yak run bundle
  bundle:auth: BRICK=auth yak run bundle
  bundle:package: BRICK=package yak run bundle
  bundle:data_layer: BRICK=data_layer yak run bundle
  bundle:domain_layer: BRICK=domain_layer yak run bundle
  bundle:presentation_layer: BRICK=presentation_layer yak run bundle
  bundle:ecosystem_presentation_layer: BRICK=ecosystem_presentation_layer yak run bundle
  bundle:notifications_feature: BRICK=notifications_feature yak run bundle
  bundle:multi_notifications_feature: BRICK=multi_notifications_feature yak run bundle
  bundle:dashboard_structure: BRICK=dashboard_structure yak run bundle
  bundle:default_dashboard_structure: BRICK=default_dashboard_structure yak run bundle
  bundle:default_structure: BRICK=default_structure yak run bundle
  bundle:map_structure: BRICK=map_structure yak run bundle
  bundle:default_map_structure: BRICK=default_map_structure yak run bundle
  bundle:model: BRICK=model yak run bundle
  bundle:all: yak run bundle:app && yak run bundle:component && yak run bundle:auth && yak run bundle:data_layer && yak run bundle:domain_layer && yak run bundle:presentation_layer && yak run bundle:notifications_feature && yak run bundle:multi_notifications_feature && yak run bundle:dashboard_structure && yak run bundle:default_dashboard_structure && yak run bundle:default_structure && yak run bundle:map_structure && yak run bundle:default_map_structure && yak run bundle:model && yak run bundle:package && yak run bundle:ecosystem_presentation_layer
  gen:app_brick:
    - command: flutter clean
      cwd: packages/app/template
    - command: dart packages/app_brick_generator/main.dart

dependencies:
  mason: ^0.1.0-dev.56
  analyzer: ^6.2.0
  args: ^2.3.1
  recase: ^4.0.0
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  io: ^1.0.3
  process_run: ^0.13.1
  path: ^1.8.2
  collection: ^1.16.0
  interact: ^2.1.1
  cli_util: ^0.4.0
  ansi_styles: ^0.3.2+1
  cli_completion: ^0.3.0
  meta: ^1.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
