name: oasis_cli
version: 2.2.0

environment:
  sdk: ">=2.15.0 <4.0.0"

executables:
  oasis: main

scripts:
  dev:test: flutter pub global activate -spath . --overwrite
  get:
    - command: flutter pub get
      cwd: packages/app/template
    - command: flutter pub get
      cwd: packages/app_brick_generator
  build:vscode: "cd extensions/vscode && vsce package patch -o digital-oasis.vsix"
  # Useful for bundling all the add bricks eg `BRICK=bloc oasis run bundle`
  bundle: mason bundle ./packages/bricks/$BRICK -o ./lib/bundles/ -t dart
  bundle:app: BRICK=app oasis run bundle
  bundle:component: BRICK=component oasis run bundle
  bundle:auth: BRICK=auth oasis run bundle
  bundle:package: BRICK=package oasis run bundle
  bundle:data_layer: BRICK=data_layer oasis run bundle
  bundle:domain_layer: BRICK=domain_layer oasis run bundle
  bundle:presentation_layer: BRICK=presentation_layer oasis run bundle
  bundle:notifications_feature: BRICK=notifications_feature oasis run bundle
  bundle:multi_notifications_feature: BRICK=multi_notifications_feature oasis run bundle
  bundle:dashboard_structure: BRICK=dashboard_structure oasis run bundle
  bundle:default_dashboard_structure: BRICK=default_dashboard_structure oasis run bundle
  bundle:default_structure: BRICK=default_structure oasis run bundle
  bundle:map_structure: BRICK=map_structure oasis run bundle
  bundle:default_map_structure: BRICK=default_map_structure oasis run bundle
  bundle:model: BRICK=model oasis run bundle
  bundle:font_family: BRICK=font_family oasis run bundle
  bundle:all: oasis run bundle:app && oasis run bundle:component && oasis run bundle:auth && oasis run bundle:data_layer && oasis run bundle:domain_layer && oasis run bundle:presentation_layer && oasis run bundle:notifications_feature && oasis run bundle:multi_notifications_feature && oasis run bundle:dashboard_structure && oasis run bundle:default_dashboard_structure && oasis run bundle:default_structure && oasis run bundle:map_structure && oasis run bundle:default_map_structure && oasis run bundle:model && oasis run bundle:font_family && oasis run bundle:package
  gen:app_brick:
    - command: flutter clean
      cwd: packages/app/template
    - command: dart packages/app_brick_generator/main.dart

dependencies:
  mason: ^0.1.0-dev.47
  analyzer: ^6.2.0
  args: ^2.3.1
  recase: ^4.0.0
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  io: ^1.0.3
  process_run: ^0.13.1
  path: ^1.8.2
  collection: ^1.16.0
  interact: ^2.1.1
  cli_util: ^0.4.0
  ansi_styles: ^0.3.2+1
  cli_completion: ^0.3.0
  meta: ^1.9.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.21.4
