// This file is generated by the Render Cli. 
// To regenerate this file, run the following command:
// `rn add fonts`

abstract class Assets {
  {{#assets}}
  static const {{#camelCase}}{{name}}{{/camelCase}} = "{{{path}}}";
  {{/assets}}
}
