// This file is generated by the Digital Oasis Cli. 
// To regenerate this file, run the following command:
// `oasis add fonts`

abstract class Assets {
  {{#assets}}
  static const {{#camelCase}}{{name}}{{/camelCase}} = "{{{path}}}";
  {{/assets}}
}
