include: all_lint_rules.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  errors:
    included_file_warning: ignore
    invalid_annotation_target: ignore
    missing_required_param: error
    avoid_print: info
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    leading_newlines_in_multiline_strings: false
    avoid_classes_with_only_static_members: false
    discarded_futures: false
    parameter_assignments: false
    avoid_positional_boolean_parameters: false
    depend_on_referenced_packages: false
    sort_constructors_first: false
    combinators_ordering: false
    eol_at_end_of_file: false
    no_leading_underscores_for_local_identifiers: false
    one_member_abstracts: false
    diagnostic_describe_all_properties: false
    prefer_double_quotes: false
    prefer_single_quotes: false
    always_specify_types: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    avoid_catches_without_on_clauses: false
    avoid_annotating_with_dynamic: false
    always_use_package_imports: false
    prefer_relative_imports: false
    sort_pub_dependencies: false
    no_default_cases: false
    avoid_final_parameters: false
    prefer_final_parameters: false
    lines_longer_than_80_chars: false
    always_put_control_body_on_new_line: false
