name: flutter_template
description: flutter template
version: 1.0.0+1
publish_to: none

scripts:
  gen: flutter pub run build_runner build --delete-conflicting-outputs
  gen:api:
    - command: flutter pub run build_runner build --delete-conflicting-outputs
      cwd: api
  get:
    - command: flutter pub get
      cwd: api
    - command: flutter pub get
  clean:
    - command: flutter clean
    - command: flutter clean
      cwd: api

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  api:
    path: ./api
  flutter_dev_overlay:
    git:
      url: github.com/Krispy145/mobile-flutter-packages.git
      path: packages/dev_overlay
      ref: flutter_dev_overlay-v0.1.5
  bloc_forms:
    git:
      url: github.com/Krispy145/mobile-flutter-packages.git
      path: packages/bloc_forms
      ref: bloc_forms-v3.3.1
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  logging: ^1.2.0
  json_annotation: ^4.8.1
  auto_route: ^7.7.1
  firebase_dynamic_links: ^5.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  arch_lints:
    git:
      url: github.com/Krispy145/mobile-flutter-packages.git
      path: packages/arch_lints
      ref: arch_lints-v3.0.0
  bloc_forms_generator:
    git:
      url: github.com/Krispy145/mobile-flutter-packages.git
      path: packages/bloc_forms_generator
      ref: bloc_forms_generator-v2.3.5
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - config/
    - assets/images/
