name: app_template
description: A new Digital Oasis Project.
version: 0.0.1+1
publish_to: none

scripts:
  gen:
    - command: flutter pub run build_runner build --delete-conflicting-outputs
    - command: flutter clean
    - command: flutter pub get
  clean:    
    - command: flutter clean
    - command: flutter pub get

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # navigation:
  #   # git:
  #   #   url: git@github.com:digital-oasis-llc-fz/navigation.git
  #   #   ref: v0.0.1
  #   path: ../../../packages/navigation
  utilities:
  #   # git:
  #   #   url: git@github.com:digital-oasis-llc-fz/utilities.git
  #   #   ref: v0.0.1
    path: ../../../../../packages/utilities
  # theme:
  #   # git:
  #   #   url: git@github.com:digital-oasis-llc-fz/theme.git
  #   #   ref: v0.0.1
  #   path: ../../../packages/theme
  flutter_gen: ^5.3.2
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  envied: ^0.5.3
  # FIREBASE START
  firebase_core: ^2.22.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.4
  firebase_dynamic_links: ^5.4.4
  # FIREBASE END
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.3.0
  build_runner:  
  flutter_gen_runner:
  auto_route_generator: ^7.3.2  
  envied_generator: ^0.5.3

flutter_gen:
  output: lib/core/assets/
  line_length: 200
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    outputs:
      class_name: Assets
    exclude: []

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/themes/
