/// This file is generated by the Unpack Cli. 
/// To regenerate this file, run the following command:
/// `up add fonts`

abstract class FontFamily {
  {{#fonts}}
  static const {{#camelCase}}{{.}}{{/camelCase}} = "{{.}}";
  {{/fonts}}
}
