/// This file is generated by the Digital Oasis Cli. 
/// To regenerate this file, run the following command:
/// `oasis add fonts`

abstract class FontFamily {
  {{#fonts}}
  static const {{#camelCase}}{{.}}{{/camelCase}} = "{{.}}";
  {{/fonts}}
}
