targets:
  $default:
    sources:
      exclude:
#        - lib/src/generated/**
      # include:
      #   - swaggers/**
    # builders:
    #   swagger_dart_code_generator:
    #     options:
    #       with_base_url: false
    #       cut_from_model_names:
    #         - Node
    #       # custom configuration options!\
    #       input_folder: swaggers/
    #       # input_urls:
    #       # - "https://raw.githubusercontent.com/epam-cross-platform-lab/swagger-dart-code-generator/master/example/input_folder/pet_service_json.json"
    #       # - "https://sweatygamer.archstaging.digitaloasis.com/api/v1/swagger"
    #       output_folder: lib/src/generated
    #       separate_models: true
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          field_rename: snake