name: api

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chopper: ^6.1.4
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  flutter_dev_overlay:
    git:
      url: git@github.com:WeAreArch/mobile-flutter-packages.git
      path: packages/dev_overlay
      ref: flutter_dev_overlay-v0.1.5
  client_api:
    git:
      url: git@github.com:WeAreArch/mobile-flutter-packages.git
      path: packages/client_api
      ref: client_api-v3.4.1

dev_dependencies:
  build_runner:
  freezed: ^2.4.1
  chopper_generator: ^6.0.3
  json_serializable: ^6.7.1
